In [1]:
import numpy as np

In [2]:
### Exercise 1
matrix = np.random.rand(5, 5)
print(matrix)

[[0.90692802 0.82864449 0.97749007 0.07109855 0.0646278 ]
 [0.46054488 0.4691479  0.33635633 0.4985873  0.72757764]
 [0.58958447 0.78632502 0.51801965 0.56201627 0.66696866]
 [0.61288471 0.34058693 0.8904977  0.722955   0.12676958]
 [0.50697752 0.9106486  0.46180422 0.90174026 0.86343868]]


In [3]:
max_value = np.max(matrix)
max_index = np.unravel_index(np.argmax(matrix, axis=None), matrix.shape)
matrix[max_index] = 0
print(matrix)

[[0.90692802 0.82864449 0.         0.07109855 0.0646278 ]
 [0.46054488 0.4691479  0.33635633 0.4985873  0.72757764]
 [0.58958447 0.78632502 0.51801965 0.56201627 0.66696866]
 [0.61288471 0.34058693 0.8904977  0.722955   0.12676958]
 [0.50697752 0.9106486  0.46180422 0.90174026 0.86343868]]


In [5]:
### Exercise 2
array1 = np.random.randint(0, 10, 5)
array2 = np.random.randint(0, 10, 5)
print(array1)
print(array2)

[4 9 2 2 3]
[7 2 8 4 7]


In [6]:
common_values = np.intersect1d(array1, array2)
print(common_values)

[2 4]


In [7]:
### Exercise 3
array = np.random.randint(0, 100, 10)
print(array)

array_sorted_asc = np.sort(array)
print(array_sorted_asc)

array_sorted_desc = np.sort(array)[::-1]
print(array_sorted_desc)

[86 57 43 61 98 14 96 46 35 66]
[14 35 43 46 57 61 66 86 96 98]
[98 96 86 66 61 57 46 43 35 14]


In [8]:
### Exercise 4
matrix = np.random.rand(4, 4)
print(matrix)

rank = np.linalg.matrix_rank(matrix)
print(rank)

[[0.68812821 0.98620723 0.38812141 0.59828108]
 [0.58518278 0.23314259 0.52256257 0.00283918]
 [0.20923027 0.35277283 0.7139935  0.45193458]
 [0.67463043 0.0425452  0.22453575 0.52736194]]
4


In [9]:
### Exercise 5
# Define the dimensions of the desired array
rows, cols = 5, 5

# Create an empty 2D array filled with zeros
array = np.zeros((rows, cols))

# Fill the border with 1s
array[0, :] = 1   # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1   # Left column
array[:, -1] = 1  # Right column

print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
