In [ ]:
import numpy as np

In [ ]:
### Exercise 1
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
### Exercise 2
original_list = [3.14, 2.17, 0, 1, 2]
integer_array = np.array(original_list, dtype=int)
print(integer_array)

[3 2 0 1 2]


In [ ]:
### Exercise 3
array = np.arange(1, 10).reshape((3, 3))
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
### Exercise 4
random_array = np.random.rand(4, 5)
print(random_array)

[[0.38845945 0.5593714  0.8273398  0.36671086 0.1530878 ]
 [0.51852448 0.16242068 0.6376295  0.22151207 0.67534829]
 [0.68016992 0.48972768 0.81236078 0.54857606 0.96060859]
 [0.09714608 0.73656147 0.69461741 0.41079331 0.31476203]]


In [ ]:
### Exercise 5
array_2d = np.array([[10, 11, 12, 13, 14],
                     [20, 21, 22, 23, 24],
                     [30, 31, 32, 33, 34],
                     [40, 41, 42, 43, 44]])

second_row = array_2d[1]
print(second_row)

[20 21 22 23 24]


In [ ]:
### Exercise 6
array_1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
reversed_array = array_1d[::-1]
print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
### Exercise 7
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
### Exercise 8
# Create an array of 10 elements all with value 4.5
array = np.full(10, 4.5)

# Calculate the sum and average
array_sum = np.sum(array)
array_avg = np.mean(array)

# Print the results
print("Array:", array)
print("Sum:", array_sum)
print("Average:", array_avg)

Array: [4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5]
Sum: 45.0
Average: 4.5


In [ ]:
### Exercise 9
one_d_array = np.arange(1, 21).reshape((5, 4))
print(one_d_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [23]:
### Exercise 10
arr = np.arange(1, 10)
# Use boolean indexing to extract odd numbers
odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]
