In [1]:
import numpy as np

In [2]:
### Exercise 1
array = np.random.rand(5, 5)
print(array)

[[0.15908839 0.05484073 0.76353054 0.34508999 0.71939057]
 [0.09805855 0.37202737 0.42790382 0.69658656 0.19340647]
 [0.16278234 0.55899099 0.4845395  0.38212816 0.24523363]
 [0.56184509 0.62068564 0.2889474  0.45115112 0.81640848]
 [0.12854766 0.27071195 0.23232693 0.64972041 0.17216346]]


In [3]:
min_value = np.min(array)
max_value = np.max(array)

print(min_value)
print(max_value)

0.054840725664169865
0.816408475492944


In [4]:
### Exercise 2
matrix = np.random.rand(3, 3)
print(matrix)

mean = np.mean(matrix)
std_dev = np.std(matrix)

normalized_matrix = (matrix - mean) / std_dev
print(normalized_matrix)

[[0.66576742 0.34880717 0.12460755]
 [0.04540878 0.35371084 0.52937991]
 [0.76675896 0.91098742 0.3497738 ]]
[[ 0.77552573 -0.39086415 -1.21590192]
 [-1.50734743 -0.37281902  0.27362994]
 [ 1.147167    1.67791688 -0.38730703]]


In [5]:
### Exercise 3
array = np.linspace(0, 10, 50, endpoint=False)
print(array)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [6]:
### Exercise4
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)

result = np.dot(matrix1, matrix2)

print(matrix1)
print(matrix2)
print(result)

[[0.16721275 0.65795081 0.23677291]
 [0.72454099 0.74769279 0.283797  ]
 [0.22652808 0.90910417 0.35478171]
 [0.21793788 0.57394427 0.56020851]
 [0.19314684 0.14920726 0.36431008]]
[[0.08343274 0.71916391]
 [0.46914885 0.92181722]
 [0.3910594  0.4281237 ]]
[[0.41522015 0.82813185]
 [0.52221114 1.33180005]
 [0.58414575 1.15282916]
 [0.50652325 0.92564331]
 [0.22858206 0.43241584]]


In [7]:
### Exercise 5
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]])

matrix2 = np.array([[2, 0],
                    [1, 2],
                    [3, 4]])

result = np.dot(matrix1, matrix2)

print(matrix1)
print(matrix2)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[2 0]
 [1 2]
 [3 4]]
[[13 16]
 [31 34]
 [49 52]
 [67 70]]
